### ISSUE TITLE
More default structure definition (`walkstyle(::Type{WalkStyle}, x)`)

### ISSUE THREAD

**Issue by chengchingwen** [chengchingwen/StructWalk.jl#3]
Currently the default behavior of `walkstyle` is expanding all the fields as children and use type as constructor, but this might not be desired for some type. Take `Dict` for example, we probably want to walk through all pairs instead of walking through fields like `slots` or `ndel`. This can be done by adding more entry to [`src/walkstyle.jl`](https://github.com/chengchingwen/StructWalk.jl/blob/main/src/walkstyle.jl). We would need a more comprehensive list of them.

**Comment by rafaqz** [comment]
Consider building on `ConstructionBase.constructorof` instead of using types directly as a constructor - it was written for exactly this kind of application. 

The problem it solves is when the object cannot be rebuilt from just the fields - it may have some additional type parameters.

**Comment by chengchingwen** [comment]
Do you have any example for the problem that `ConstructionBase.constructorof` solved? It sounds like it's for rewriting the [default `walkstyle` behavior](https://github.com/chengchingwen/StructWalk.jl/blob/main/src/StructWalk.jl#L38)?

**Comment by rafaqz** [comment]
See Flatten.jl, Setfield.jl, Accessors.jl  BamBang.jl as examples. They all build on ConstructionBase.jl.

But `constructorof` is just used for object construction. You mentioned that you use the type as constructor. Often the wrapper type is not the full constructor. It may have additional type parameters like the array size in static arrays - that you cant get from the fields. 
See: https://github.com/JuliaObjects/ConstructionBaseExtras.jl/blob/51f29aff6fc2fb2fc7a47380d1342b3c413b7bec/src/staticarrays.jl

Or you may want to rebuild the object with differently typed fields, so the full type won't work as a constructor either. `constructorof` solves that problem by defing defaults but allowing custom constructors to be defined.

You may also want an additional method like `walkstyle`, but the reason we wrote and use ConstructionBase.jl is to reduce the number of these methods people have to define for an object. `getproperties` and `setproperties` are also useful methods.

**Comment by chengchingwen** [comment]
I kind of see your point, but there is a fundamental different between StructWalk.jl and friends. Here we focus on the transformation, so it's likely the transformed fields are not having the same type as origin. For example, we might "walk" through a `Dict{String, Int}` and get a `Dict{Symbol, Float64}` in return. It wouldn't work if we always keep the type parameter in this case. And since the returned type is based on the transform function, it's not decidable with the input object itself. It's possible there are some parameters that are agnostic to the transform, but  then we would want to have high controllability over the return value of `constructorof` (e.g. how could I get the constructor that only inherit the fieldtype-agnostic parameters?), otherwise it would still require a custom definition in StructWalk.jl and the situation remain the same.

OTOH, We actually want/encourage people to define their own `WalkStyle`. The default definition we do here is just to keep the semantic consistent. Like the example in the opening comment, when we talk about "walk"ing through a `Dict`, we are more likely to be referring to "walk"ing through it's pairs, not the fields like `slots` etc.. Even if we do want that behavior, we can just define a new `WalkStyle` and overload the `walkstyle`.

It seems that ConstructionBase.jl doesn't suit well here, correct me if I'm wrong.

**Comment by rafaqz** [comment]
All the other packages allow field types to change too, similar to what you are doing. 

The type parameters are not kept by default. But for example a `SMatrix` the shape `S`  type parameter is independent of the fields - and thats where we need a common custom constructor. One that keeps `S`, and replaces the other parameters.

As I mentioned you may still need walkstyle for `Dict` etc, but `constructorof` will give you a lot for free.

**Comment by chengchingwen** [comment]
I see, I think you've got a point. It does worth switching the default to `constructorof`, so the remaining issue here would be missing those definition with inconsistent semantics like `Dict`

**Comment by chengchingwen** [comment]
closed by #4
